### ISSUE TITLE
Why does the following situation give different results?

### ISSUE THREAD

**Issue by WuGUOJ** [DeronW/beautifulsoup#10]
`from bs4 import BeautifulSoup`
`import re`

`html = "<p>相关阅读：《 <a>向前迈出一大步 试驾比亚迪宋Pro燃油版 </a> 》</p>"`
`soup = BeautifulSoup(html, "lxml")`
`tags = soup.find_all("p", text=re.compile(r"相关阅读"))`
`print(tags)   # return []`

but this html can get result
`html = "<p>相关阅读：《 向前迈出一大步 试驾比亚迪宋Pro燃油版 》</p>"`

**Comment by delong8** [comment]
这个项目只是文档翻译，如果是解析问题可以到讨论组提问  https://groups.google.com/g/beautifulsoup
