### ISSUE TITLE
tag中包含的字符串可直接编辑

### ISSUE THREAD

**Issue by Chellane** [DeronW/beautifulsoup#13]
![image](https://user-images.githubusercontent.com/29483859/115959909-307eb680-a541-11eb-8f60-bae0919878cd.png)
这里可以直接通过soup.a.string = "other string" 来直接修改a标签的字符串内容：
![image](https://user-images.githubusercontent.com/29483859/115959981-923f2080-a541-11eb-90c4-ffa28757188e.png)

**Comment by delong8** [comment]
这个项目只是文档翻译，如果是解析问题可以到讨论组提问 https://groups.google.com/g/beautifulsoup
