### ISSUE TITLE
错别字

### ISSUE THREAD

**Issue by syunaht** [DeronW/beautifulsoup#16]
https://beautifulsoup.readthedocs.io/zh_CN/v4.4.0/index.html#id35
字符窜->字符串
>重申: 搜索 name 参数的值可以使任一类型的 过滤器 ,字符窜,正则表达式,列表,方法或是 True .

感谢翻译！

**Comment by delong8** [comment]
已经更新翻译，提交给讨论组 https://groups.google.com/g/beautifulsoup/c/2U4r9sxFw7w
