### ISSUE TITLE
Wrong link

### ISSUE THREAD

**Issue by realroyxu** [DeronW/beautifulsoup#17]
中文手册页面的一个链接被错误地指向了百度
![Snipaste_2022-06-23_08-51-03](https://user-images.githubusercontent.com/75887166/175184529-c5fb2e14-15d9-435c-ac4a-9a2c02714b51.png)

**Comment by delong8** [comment]
已经更新翻译，提交给讨论组， https://groups.google.com/g/beautifulsoup/c/2U4r9sxFw7w
