### ISSUE TITLE
add pdf output 

### ISSUE THREAD

**Issue by WanderMax** [DeronW/beautifulsoup#4]
could you please add pdf output file? it has only html file currently.
thanks.

**Comment by delong8** [comment]
@WanderMax OK I will do it soon

**Comment by delong8** [comment]
@WanderMax 

查看这个连接,  或者master

pdf/ 目录下包含了一个 BeautifulSoup-x.x.x.pdf 文件

https://github.com/DeronW/beautifulsoup/releases/tag/4.4.0p

**Comment by WanderMax** [comment]
could you please add chapter feature?
and thanks for your support.

**Comment by delong8** [comment]
OK, I will try
