### ISSUE TITLE
发现了些小瑕疵

### ISSUE THREAD

**Issue by Just4Learning** [DeronW/beautifulsoup#5]
### 【1】文字修改
![Image text](https://github.com/Just4Learning/Learning/blob/master/dir4pics/and.png)
这里译者应该想表达的是“find_next_siblings()和find_next_sibling()”的意思。

### 【2】CSS选择器使用的一个示例报错
![Image text](https://github.com/Just4Learning/Learning/blob/master/dir4pics/code_e.png)
如果照着写作【soup.select("p nth-of-type(3)"】会报错：【ValueError: Unsupported or invalid CSS selector: "nth-of-type(3)"】。
解决的办法可能是写作【soup.select("p:nth-of-type(3)"】。

**Comment by delong8** [comment]
多谢指正, 已经修复

见最新文档 http://beautifulsoup.readthedocs.io/zh_CN/latest/
