### ISSUE TITLE
错别字

### ISSUE THREAD

**Issue by myuanz** [DeronW/beautifulsoup#6]
在[此处](http://beautifulsoup.readthedocs.io/zh_CN/v4.4.0/#get-text)
> 如果只想得到tag中包含的文本内容,那么可以嗲用 get_text() 方法,这个方法获取到tag中包含的所有文版内容包括子孙tag中的内容,并将结果作为Unicode字符串返回:

嗲用->调用.
感谢您的翻译

**Comment by delong8** [comment]
多谢提醒，文案已经修改，近期会更新上去。
