### ISSUE TITLE
like this can't get data

### ISSUE THREAD

**Issue by zengaorong** [DeronW/beautifulsoup#8]
<!DOCTYPE html>
<html>
<body id="wrapper">
</body>
</html>

'<!DOCTYPE html>\r<html>\r<body id="wrapper">\r</body>\r</html>'
print '<!DOCTYPE html>\r<html>\r<body id="wrapper">\r</body>\r</html>'

**Comment by delong8** [comment]
具体是指什么？ 是翻译的问题，还是功能上的问题？
